<?php 

function WeatherUrl($url){
		$cn = curl_init();
		curl_setopt($cn, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($cn, CURLOPT_URL, $url);    
		$weatherdata = curl_exec($cn); 
		curl_close($cn); 
		return $weatherdata;
}

if (isset($_POST['submit'])) { 

$location = $_POST['location'];

$url="http://api.openweathermap.org/data/2.5/weather?q=". $location .",IN,IN&units=metric&appid=a44462951ffa5ef002cfa0260c639cf0";


$response=WeatherUrl($url);

$data = json_decode($response);
date_default_timezone_set("Asia/Calcutta");
$currentTime = time();

if ($data->cod == 404) {
	$message = $data->message;
} else { 

$message=NULL;
$location = $data->name;
$type = $data->weather[0]->description;
$country = $data->sys->country;
$temp = $data->main->temp . '℃';



$minimum_temp = $data->main->temp_min . '℃';
$maximum_temp = $data->main->temp_max . '℃';
$feels_like = $data->main->feels_like . '℃';
$pressure = $data->main->pressure . '℃';
$humidity = $data->main->humidity . '℃';
$windspeed = $data->wind->speed . 'm/s';

}
}

?> 

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Weathfy | Free weather app</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <link rel="icon" type="image/x-icon" href="favicon.png">
	<link rel="stylesheet" type="text/css" href="style.css">
  <link rel="stylesheet" type="text/css" href="index.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<div class="details">
	<div class="logo"><a href="https://weathfy.hstn.me/"><img style="height: 200px;margin-top: -40px;" src="logo.png"></a></div>
</div><br>
<div class="mains" style="z-index: 1000;">
<h4 style="text-align: center;color: yellow;font-family: sans-serif;"><span style="color: white;">Note:</span> Only Major cities are listed below</h4>
<h5 style="text-align: center;color: yellow;font-family: sans-serif;">However you can search most of the cities and towns!</h5>
<form method="post" action="index.php">
  <div class="search-box">
    <div class="row">
      <input type="text" id="input-box" placeholder="Search For City ex. ( vasco )" name="location" autocomplete="off">
      <button type="submit" name="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </div>
    <div class="result-box">

    </div>
  </div>
</form>
</div>
</div>
<br>

<div class="container">
        <div class="weather-container">
        	<?php if (isset($_POST['submit'])) { ?>
        		<?php if ($message == NULL){ ?>
        			<div class="details">
            		<div><span style="color: gainsboro;"><?php echo date("l g:i a", $currentTime); ?></span></div>
            		<div><span style="color: gainsboro;"><?php echo date("jS F, Y",$currentTime); ?></span></div>
        			</div>
        		<div class="location" style="font-family: Kanit;color: floralwhite;font-family: 'Poppins', sans-serif;"><?php
    					echo "Currently in ". $location; ?>
 						</div>
        		<div class="temperature" style="font-family: 'Poppins', sans-serif;font-weight: bolder;"><?php
    echo $temp;  ?></div>
        <img
                src="https://openweathermap.org/img/w/<?php echo $data->weather[0]->icon; ?>.png"
                class="weather-icon" /><span
                class="min-temperature"></span>
        <div class="description"><?php echo $type; ?></div>
        <div class="details">
            <div>Humidity: 60%</div>
            <div>Wind: 10 km/h</div>
            <div>Pressure: 1015 hPa</div>
          <?php } else { echo "<h2 style='color:white;text-transform: capitalize;font-family: sans-serif;'>".$message."</h2>"; } } else { echo "<h2 style='font-size: 1.9em;color:  white;text-transform: capitalize;font-family: sans-serif;'>Enter city name to check weather</h2>"; } ?>
        </div>
    </div><br><br>
    <div class="footer" style="text-align: center;color: white; font-family: 'Wellfleet', monospace;font-size: 20px;">Made by <a style="text-decoration: underline;color: white;" href="https://www.instagram.com/siddhesh_gawade11/">Siddhesh Gawade </a> &copy; <?php echo date("Y")."-". date("y")+1; ?></div>

<script>
  let availableCities = [
'Mumbai',
'Delhi',
'Bengaluru',
'Ahmedabad',
'Hyderabad',
'Chennai',
'Kolkata',
'Pune',
'Jaipur',
'Surat',
'Lucknow',
'Kanpur',
'Nagpur',
'Patna',
'Indore',
'Thane',
'Bhopal',
'Visakhapatnam',
'Vadodara',
'Firozabad',
'Ludhiana',
'Rajkot',
'Agra',
'Siliguri',
'Nashik',
'Faridabad',
'Patiala',
'Meerut',
'Kalyan-Dombivali',
'Vasai-Virar',
'Varanasi',
'Srinagar',
'Dhanbad',
'Jodhpur',
'Amritsar',
'Raipur',
'Allahabad',
'Coimbatore',
'Jabalpur',
'Gwalior',
'Vijayawada',
'Madurai',
'Guwahati',
'Chandigarh',
'Hubli-Dharwad',
'Amroha',
'Moradabad',
'Gurgaon',
'Aligarh',
'Solapur',
'Ranchi',
'Jalandhar',
'Tiruchirappalli',
'Bhubaneswar',
'Salem',
'Warangal',
'Mira-Bhayandar',
'Thiruvananthapuram',
'Bhiwandi',
'Saharanpur',
'Guntur',
'Amravati',
'Bikaner',
'Noida',
'Jamshedpur',
'Bhilai Nagar',
'Cuttack',
'Kochi',
'Udaipur',
'Bhavnagar',
'Dehradun',
'Asansol',
'Nanded-Waghala',
'Ajmer',
'Jamnagar',
'Ujjain',
'Sangli',
'Loni',
'Jhansi',
'Pondicherry',
'Nellore',
'Jammu',
'Belagavi',
'Raurkela',
'Mangaluru',
'Tirunelveli',
'Malegaon',
'Gaya',
'Tiruppur',
'Davanagere',
'Kozhikode',
'Akola',
'Kurnool',
'Bokaro Steel City',
'Rajahmundry',
'Ballari',
'Agartala',
'Bhagalpur',
'Latur',
'Dhule',
'Korba',
'Bhilwara',
'Brahmapur',
'Mysore',
'Muzaffarpur',
'Ahmednagar',
'Kollam',
'Raghunathganj',
'Bilaspur',
'Shahjahanpur',
'Thrissur',
'Alwar',
'Kakinada',
'Nizamabad',
'Sagar',
'Tumkur',
'Hisar',
'Rohtak',
'Panipat',
'Darbhanga',
'Kharagpur',
'Aizawl',
'Ichalkaranji',
'Tirupati',
'Karnal',
'Bathinda',
'Rampur',
'Shivamogga',
'Ratlam',
'Modinagar',
'Durg',
'Shillong',
'Imphal',
'Hapur',
'Ranipet',
'Anantapur',
'Arrah',
'Karimnagar',
'Parbhani',
'Etawah',
'Bharatpur',
'Begusarai',
'New Delhi',
'Chhapra',
'Kadapa',
'Ramagundam',
'Pali',
'Satna',
'Vizianagaram',
'Katihar',
'Hardwar',
'Sonipat',
'Nagercoil',
'Thanjavur',
'Murwara (Katni)',
'Naihati',
'Sambhal',
'Nadiad',
'Yamunanagar',
'English Bazar',
'Eluru',
'Munger',
'Panchkula',
'Raayachuru',
'Panvel',
'Deoghar',
'Ongole',
'Nandyal',
'Morena',
'Bhiwani',
'Porbandar',
'Palakkad',
'Anand',
'Purnia',
'Baharampur',
'Barmer',
'Morvi',
'Orai',
'Bahraich',
'Sikar',
'Vellore',
'Singrauli',
'Khammam',
'Mahesana',
'Silchar',
'Sambalpur',
'Rewa',
'Unnao',
'Hugli-Chinsurah',
'Raiganj',
'Phusro',
'Adityapur',
'Alappuzha',
'Bahadurgarh',
'Machilipatnam',
'Rae Bareli',
'Jalpaiguri',
'Bharuch',
'Pathankot',
'Hoshiarpur',
'Baramula',
'Adoni',
'Jind',
'Tonk',
'Tenali',
'Kancheepuram',
'Vapi',
'Sirsa',
'Navsari',
'Mahbubnagar',
'Puri',
'Robertson Pet',
'Erode',
'Batala',
'Haldwani-cum-Kathgodam',
'Vidisha',
'Saharsa',
'Thanesar',
'Chittoor',
'Veraval',
'Lakhimpur',
'Sitapur',
'Hindupur',
'Santipur',
'Balurghat',
'Ganjbasoda',
'Moga',
'Proddatur',
'Srinagar',
'Medinipur',
'Habra',
'Sasaram',
'Hajipur',
'Bhuj',
'Shivpuri',
'Ranaghat',
'Shimla',
'Tiruvannamalai',
'Kaithal',
'Rajnandgaon',
'Godhra',
'Hazaribag',
'Bhimavaram',
'Mandsaur',
'Dibrugarh',
'Kolar',
'Bankura',
'Mandya',
'Dehri-on-Sone',
'Madanapalle',
'Malerkotla',
'Lalitpur',
'Bettiah',
'Pollachi',
'Khanna',
'Neemuch',
'Palwal',
'Palanpur',
'Guntakal',
'Nabadwip',
'Udupi',
'Jagdalpur',
'Motihari',
'Pilibhit',
'Dimapur',
'Mohali',
'Sadulpur',
'Rajapalayam',
'Dharmavaram',
'Kashipur',
'Sivakasi',
'Darjiling',
'Chikkamagaluru',
'Gudivada',
'Baleshwar Town',
'Mancherial',
'Srikakulam',
'Adilabad',
'Yavatmal',
'Barnala',
'Nagaon',
'Narasaraopet',
'Raigarh',
'Roorkee',
'Valsad',
'Ambikapur',
'Giridih',
'Chandausi',
'Purulia',
'Patan',
'Bagaha',
'Hardoi ',
'Achalpur',
'Osmanabad',
'Deesa',
'Nandurbar',
'Azamgarh',
'Ramgarh',
'Firozpur',
'Baripada Town',
'Karwar',
'Siwan',
'Rajampet',
'Pudukkottai',
'Anantnag',
'Tadpatri',
'Satara',
'Bhadrak',
'Kishanganj',
'Suryapet',
'Wardha',
'Ranebennuru',
'Amreli',
'Neyveli (TS)',
'Jamalpur',
'Marmagao',
'Udgir',
'Tadepalligudem',
'Nagapattinam',
'Buxar',
'Aurangabad',
'Jehanabad',
'Phagwara',
'Khair',
'Sawai Madhopur',
'Kapurthala',
'Chilakaluripet',
'Aurangabad',
'Malappuram',
'Rewari',
'Nagaur',
'Sultanpur',
'Nagda',
'Port Blair',
'Lakhisarai',
'Panaji',
'Tinsukia',
'Itarsi',
'Kohima',
'Balangir',
'Nawada',
'Jharsuguda',
'Jagtial',
'Viluppuram',
'Amalner',
'Zirakpur',
'Tanda',
'Tiruchengode',
'Nagina',
'Yemmiganur',
'Vaniyambadi',
'Sarni',
'Theni Allinagaram',
'Margao',
'Akot',
'Sehore',
'Mhow Cantonment',
'Kot Kapura',
'Makrana',
'Pandharpur',
'Miryalaguda',
'Shamli',
'Seoni',
'Ranibennur',
'Kadiri',
'Shrirampur',
'Rudrapur',
'Parli',
'Najibabad',
'Nirmal',
'Udhagamandalam',
'Shikohabad',
'Jhumri Tilaiya',
'Aruppukkottai',
'Ponnani',
'Jamui',
'Sitamarhi',
'Chirala',
'Anjar',
'Karaikal',
'Hansi',
'Anakapalle',
'Mahasamund',
'Faridkot',
'Saunda',
'Dhoraji',
'Paramakudi',
'Balaghat',
'Sujangarh',
'Khambhat',
'Muktsar',
'Rajpura',
'Kavali',
'Dhamtari',
'Ashok Nagar',
'Sardarshahar',
'Mahuva',
'Bargarh',
'Kamareddy',
'Sahibganj',
'Kothagudem',
'Ramanagaram',
'Gokak',
'Tikamgarh',
'Araria',
'Rishikesh',
'Shahdol',
'Medininagar (Daltonganj)',
'Arakkonam',
'Washim',
'Sangrur',
'Bodhan',
'Fazilka',
'Palacole',
'Keshod',
'Sullurpeta',
'Wadhwan',
'Gurdaspur',
'Vatakara',
'Tura',
'Narnaul',
'Kharar',
'Yadgir',
'Ambejogai',
'Ankleshwar',
'Savarkundla',
'Paradip',
'Virudhachalam',
'Kanhangad',
'Kadi',
'Srivilliputhur',
'Gobindgarh',
'Tindivanam',
'Mansa',
'Taliparamba',
'Manmad',
'Tanuku',
'Rayachoti',
'Virudhunagar',
'Koyilandy',
'Jorhat',
'Karur',
'Valparai',
'Srikalahasti',
'Neyyattinkara',
'Bapatla',
'Fatehabad',
'Malout',
'Sankarankovil',
'Tenkasi',
'Ratnagiri',
'Rabkavi Banhatti',
'Sikandrabad',
'Chaibasa',
'Chirmiri',
'Palwancha',
'Bhawanipatna',
'Kayamkulam',
'Pithampur',
'Nabha',
'Shahabad, Hardoi',
'Dhenkanal',
'Uran Islampur',
'Gopalganj',
'Bongaigaon City',
'Palani',
'Pusad',
'Sopore',
'Pilkhuwa',
'Tarn Taran',
'Renukoot',
'Mandamarri',
'Shahabad',
'Barbil',
'Koratla',
'Madhubani',
'Arambagh',
'Gohana',
'Ladnu',
'Pattukkottai',
'Sirsi',
'Sircilla',
'Tamluk',
'Jagraon',
'AlipurdUrban Agglomerationr',
'Alirajpur',
'Tandur',
'Naidupet',
'Tirupathur',
'Tohana',
'Ratangarh',
'Dhubri',
'Masaurhi',
'Visnagar',
'Vrindavan',
'Nokha',
'Nagari',
'Narwana',
'Ramanathapuram',
'Ujhani',
'Samastipur',
'Laharpur',
'Sangamner',
'Nimbahera',
'Siddipet',
'Suri',
'Diphu',
'Jhargram',
'Shirpur-Warwade',
'Tilhar',
'Sindhnur',
'Udumalaipettai',
'Malkapur',
'Wanaparthy',
'Gudur',
'Kendujhar',
'Mandla',
'Mandi',
'Nedumangad',
'North Lakhimpur',
'Vinukonda',
'Tiptur',
'Gobichettipalayam',
'Sunabeda',
'Wani',
'Upleta',
'Narasapuram',
'Nuzvid',
'Tezpur',
'Una',
'Markapur',
'Sheopur',
'Thiruvarur',
'Sidhpur',
'Sahaswan',
'Suratgarh',
'Shajapur',
'Rayagada',
'Lonavla',
'Ponnur',
'Kagaznagar',
'Gadwal',
'Bhatapara',
'Kandukur',
'Sangareddy',
'Unjha',
'Lunglei',
'Karimganj',
'Kannur',
'Bobbili',
'Mokameh',
'Talegaon Dabhade',
'Anjangaon',
'Mangrol',
'Sunam',
'Gangarampur',
'Thiruvallur',
'Tirur',
'Rath',
'Jatani',
'Viramgam',
'Rajsamand',
'Yanam',
'Kottayam',
'Panruti',
'Dhuri',
'Namakkal',
'Kasaragod',
'Modasa',
'Rayadurg',
'Supaul',
'Kunnamkulam',
'Umred',
'Bellampalle',
'Sibsagar',
'Mandi Dabwali',
'Ottappalam',
'Dumraon',
'Samalkot',
'Jaggaiahpet',
'Goalpara',
'Tuni',
'Lachhmangarh',
'Bhongir',
'Amalapuram',
'Firozpur Cantt.',
'Vikarabad',
'Thiruvalla',
'Sherkot',
'Palghar',
'Shegaon',
'Jangaon',
'Bheemunipatnam',
'Panna',
'Thodupuzha',
'KathUrban Agglomeration',
'Palitana',
'Arwal',
'Venkatagiri',
'Kalpi',
'Rajgarh (Churu)',
'Sattenapalle',
'Arsikere',
'Ozar',
'Thirumangalam',
'Petlad',
'Nasirabad',
'Phaltan',
'Rampurhat',
'Nanjangud',
'Forbesganj',
'Tundla',
'BhabUrban Agglomeration',
'Sagara',
'Pithapuram',
'Sira',
'Bhadrachalam',
'Charkhi Dadri',
'Chatra',
'Palasa Kasibugga',
'Nohar',
'Yevla',
'Sirhind Fatehgarh Sahib',
'Bhainsa',
'Parvathipuram',
'Shahade',
'Chalakudy',
'Narkatiaganj',
'Kapadvanj',
'Macherla',
'Raghogarh-Vijaypur',
'Rupnagar',
'Naugachhia',
'Sendhwa',
'Byasanagar',
'Sandila',
'Gooty',
'Salur',
'Nanpara',
'Sardhana',
'Vita',
'Gumia',
'Puttur',
'Jalandhar Cantt.',
'Nehtaur',
'Changanassery',
'Mandapeta',
'Dumka',
'Seohara',
'Umarkhed',
'Madhupur',
'Vikramasingapuram',
'Punalur',
'Kendrapara',
'Sihor',
'Nellikuppam',
'Samana',
'Warora',
'Nilambur',
'Rasipuram',
'Ramnagar',
'Jammalamadugu',
'Nawanshahr',
'Thoubal',
'Athni',
'Cherthala',
'Sidhi',
'Farooqnagar',
'Peddapuram',
'Chirkunda',
'Pachora',
'Madhepura',
'Pithoragarh',
'Tumsar',
'Phalodi',
'Tiruttani',
'Rampura Phul',
'Perinthalmanna',
'Padrauna',
'Pipariya',
'Dalli-Rajhara',
'Punganur',
'Mattannur',
'Mathura',
'Thakurdwara',
'Nandivaram-Guduvancheri',
'Mulbagal',
'Manjlegaon',
'Wankaner',
'Sillod',
'Nidadavole',
'Surapura',
'Rajagangapur',
'Sheikhpura',
'Parlakhemundi',
'Kalimpong',
'Siruguppa',
'Arvi',
'Limbdi',
'Barpeta',
'Manglaur',
'Repalle',
'Mudhol',
'Shujalpur',
'Mandvi',
'Thangadh',
'Sironj',
'Nandura',
'Shoranur',
'Nathdwara',
'Periyakulam',
'Sultanganj',
'Medak',
'Narayanpet',
'Raxaul Bazar',
'Rajauri',
'Pernampattu',
'Nainital',
'Ramachandrapuram',
'Vaijapur',
'Nangal',
'Sidlaghatta',
'Punch',
'Pandhurna',
'Wadgaon Road',
'Talcher',
'Varkala',
'Pilani',
'Nowgong',
'Naila Janjgir',
'Mapusa',
'Vellakoil',
'Merta City',
'Sivaganga',
'Mandideep',
'Sailu',
'Vyara',
'Kovvur',
'Vadalur',
'Nawabganj',
'Padra',
'Sainthia',
'Siana',
'Shahpur',
'Sojat',
'Noorpur',
'Paravoor',
'Murtijapur',
'Ramnagar',
'Sundargarh',
'Taki',
'Saundatti-Yellamma',
'Pathanamthitta',
'Wadi',
'Rameshwaram',
'Tasgaon',
'Sikandra Rao',
'Sihora',
'Tiruvethipuram',
'Tiruvuru',
'Mehkar',
'Peringathur',
'Perambalur',
'Manvi',
'Zunheboto',
'Mahnar Bazar',
'Attingal',
'Shahbad',
'Puranpur',
'Nelamangala',
'Nakodar',
'Lunawada',
'Murshidabad',
'Mahe',
'Lanka',
'Rudauli',
'Tuensang',
'Lakshmeshwar',
'Zira',
'Yawal',
'Thana Bhawan',
'Ramdurg',
'Pulgaon',
'Sadasivpet',
'Nargund',
'Neem-Ka-Thana',
'Memari',
'Nilanga',
'Naharlagun',
'Pakaur',
'Wai',
'Tarikere',
'Malavalli',
'Raisen',
'Lahar',
'Uravakonda',
'Savanur',
'Sirohi',
'Udhampur',
'Umarga',
'Pratapgarh',
'Lingsugur',
'Usilampatti',
'Palia Kalan',
'Wokha',
'Rajpipla',
'Vijayapura',
'Rawatbhata',
'Sangaria',
'Paithan',
'Rahuri',
'Patti',
'Zaidpur',
'Lalsot',
'Maihar',
'Vedaranyam',
'Nawapur',
'Solan',
'Vapi',
'Sanawad',
'Warisaliganj',
'Revelganj',
'Sabalgarh',
'Tuljapur',
'Simdega',
'Musabani',
'Kodungallur',
'Phulabani',
'Umreth',
'Narsipatnam',
'Nautanwa',
'Rajgir',
'Yellandu',
'Sathyamangalam',
'Pilibanga',
'Morshi',
'Pehowa',
'Sonepur',
'Pappinisseri',
'Zamania',
'Mihijam',
'Purna',
'Puliyankudi',
'Shikarpur, Bulandshahr',
'Umaria',
'Porsa',
'Naugawan Sadat',
'Fatehpur Sikri',
'Manuguru',
'Udaipur',
'Pipar City',
'Pattamundai',
'Nanjikottai',
'Taranagar',
'Yerraguntla',
'Satana',
'Sherghati',
'Sankeshwara',
'Madikeri',
'Thuraiyur',
'Sanand',
'Rajula',
'Kyathampalle',
'Shahabad, Rampur',
'Tilda Newra',
'Narsinghgarh',
'Chittur-Thathamangalam',
'Malaj Khand',
'Sarangpur',
'Robertsganj',
'Sirkali',
'Radhanpur',
'Tiruchendur',
'Utraula',
'Patratu',
'Vijainagar, Ajmer',
'Periyasemur',
'Pathri',
'Sadabad',
'Talikota',
'Sinnar',
'Mungeli',
'Sedam',
'Shikaripur',
'Sumerpur',
'Sattur',
'Sugauli',
'Lumding',
'Vandavasi',
'Titlagarh',
'Uchgaon',
'Mokokchung',
'Paschim Punropara',
'Sagwara',
'Ramganj Mandi',
'Tarakeswar',
'Mahalingapura',
'Dharmanagar',
'Mahemdabad',
'Manendragarh',
'Uran',
'Tharamangalam',
'Tirukkoyilur',
'Pen',
'Makhdumpur',
'Maner',
'Oddanchatram',
'Palladam',
'Mundi',
'Nabarangapur',
'Mudalagi',
'Samalkha',
'Nepanagar',
'Karjat',
'Ranavav',
'Pedana',
'Pinjore',
'Lakheri',
'Pasan',
'Puttur',
'Vadakkuvalliyur',
'Tirukalukundram',
'Mahidpur',
'Mussoorie',
'Muvattupuzha',
'Rasra',
'Udaipurwati',
'Manwath',
'Adoor',
'Uthamapalayam',
'Partur',
'Nahan',
'Ladwa',
'Mankachar',
'Nongstoin',
'Losal',
'Sri Madhopur',
'Ramngarh',
'Mavelikkara',
'Rawatsar',
'Rajakhera',
'Lar',
'Lal Gopalganj Nindaura',
'Muddebihal',
'Sirsaganj',
'Shahpura',
'Surandai',
'Sangole',
'Pavagada',
'Tharad',
'Mansa',
'Umbergaon',
'Mavoor',
'Nalbari',
'Talaja',
'Malur',
'Mangrulpir',
'Soro',
'Shahpura',
'Vadnagar',
'Raisinghnagar',
'Sindhagi',
'Sanduru',
'Sohna',
'Manavadar',
'Pihani',
'Safidon',
'Risod',
'Rosera',
'Sankari',
'Malpura',
'Sonamukhi',
'Shamsabad, Agra',
'Nokha',
'PandUrban Agglomeration',
'Mainaguri',
'Afzalpur',
'Shirur',
'Salaya',
'Shenkottai',
'Pratapgarh',
'Vadipatti',
'Nagarkurnool',
'Savner',
'Sasvad',
'Rudrapur',
'Soron',
'Sholingur',
'Pandharkaoda',
'Perumbavoor',
'Maddur',
'Nadbai',
'Talode',
'Shrigonda',
'Madhugiri',
'Tekkalakote',
'Seoni-Malwa',
'Shirdi',
'SUrban Agglomerationr',
'Terdal',
'Raver',
'Tirupathur',
'Taraori',
'Mukhed',
'Manachanallur',
'Rehli',
'Sanchore',
'Rajura',
'Piro',
'Mudabidri',
'Vadgaon Kasba',
'Nagar',
'Vijapur',
'Viswanatham',
'Polur',
'Panagudi',
'Manawar',
'Tehri',
'Samdhan',
'Pardi',
'Rahatgarh',
'Panagar',
'Uthiramerur',
'Tirora',
'Rangia',
'Sahjanwa',
'Wara Seoni',
'Magadi',
'Rajgarh (Alwar)',
'Rafiganj',
'Tarana',
'Rampur Maniharan',
'Sheoganj',
'Raikot',
'Pauri',
'Sumerpur',
'Navalgund',
'Shahganj',
'Marhaura',
'Tulsipur',
'Sadri',
'Thiruthuraipoondi',
'Shiggaon',
'Pallapatti',
'Mahendragarh',
'Sausar',
'Ponneri',
'Mahad',
'Lohardaga',
'Tirwaganj',
'Margherita',
'Sundarnagar',
'Rajgarh',
'Mangaldoi',
'Renigunta',
'Longowal',
'Ratia',
'Lalgudi',
'Shrirangapattana',
'Niwari',
'Natham',
'Unnamalaikadai',
'PurqUrban Agglomerationzi',
'Shamsabad, Farrukhabad',
'Mirganj',
'Todaraisingh',
'Warhapur',
'Rajam',
'Urmar Tanda',
'Lonar',
'Powayan',
'P.N.Patti',
'Palampur',
'Srisailam Project (Right Flank Colony) Township',
'Sindagi',
'Sandi',
'Vaikom',
'Malda',
'Tharangambadi',
'Sakaleshapura',
'Lalganj',
'Malkangiri',
'Rapar',
'Mauganj',
'Todabhim',
'Srinivaspur',
'Murliganj',
'Reengus',
'Sawantwadi',
'Tittakudi',
'Lilong',
'Rajaldesar',
'Pathardi',
'Achhnera',
'Pacode',
'Naraura',
'Nakur',
'Palai',
'Morinda, India',
'Manasa',
'Nainpur',
'Sahaspur',
'Pauni',
'Prithvipur',
'Ramtek',
'Silapathar',
'Songadh',
'Safipur',
'Sohagpur',
'Mul',
'Sadulshahar',
'Phillaur',
'Sambhar',
'Prantij',
'Nagla',
'Pattran',
'Mount Abu',
'Reoti',
'Tenu dam-cum-Kathhara',
'Panchla',
'Sitarganj',
'Pasighat',
'Motipur',
'O Valley',
'Raghunathpur',
'Suriyampalayam',
'Qadian',
'Rairangpur',
'Silvassa',
'Nowrozabad (Khodargama)',
'Mangrol',
'Soyagaon',
'Sujanpur',
'Manihari',
'Sikanderpur',
'Mangalvedhe',
'Phulera',
'Ron',
'Sholavandan',
'Saidpur',
'Shamgarh',
'Thammampatti',
'Maharajpur',
'Multai',
'Mukerian',
'Sirsi',
'Purwa',
'Sheohar',
'Namagiripettai',
'Parasi',
'Lathi',
'Lalganj',
'Narkhed',
'Mathabhanga',
'Shendurjana',
'Peravurani',
'Mariani',
'Phulpur',
'Rania',
'Pali',
'Pachore',
'Parangipettai',
'Pudupattinam',
'Panniyannur',
'Maharajganj',
'Rau',
'Monoharpur',
'Mandawa',
'Marigaon',
'Pallikonda',
'Pindwara',
'Shishgarh',
'Patur',
'Mayang Imphal',
'Mhowgaon',
'Guruvayoor',
'Mhaswad',
'Sahawar',
'Sivagiri',
'Mundargi',
'Punjaipugalur',
'Kailasahar',
'Samthar',
'Sakti',
'Sadalagi',
'Silao',
'Mandalgarh',
'Loha',
'Pukhrayan',
'Padmanabhapuram',
'Belonia',
'Saiha',
'Srirampore',
'Talwara',
'Puthuppally',
'Khowai',
'Vijaypur',
'Takhatgarh',
'Thirupuvanam',
'Adra',
'Piriyapatna',
'Obra',
'Adalaj',
'Nandgaon',
'Barh',
'Chhapra',
'Panamattom',
'Niwai',
'Bageshwar',
'Tarbha',
'Adyar',
'Narsinghgarh',
'Warud',
'Asarganj',
'Sarsod',
];

const resultsBox = document.querySelector(".result-box");
const inputBox = document.getElementById("input-box");

inputBox.onkeyup = function(){
  let result = [];
  let input = inputBox.value;
  if(input.length){
    result = availableCities.filter((keyword)=>{
      return keyword.toLowerCase().includes(input.toLowerCase());
    });
    console.log(result);
  }
  display(result);
}

function display(result){
  const content = result.map((list)=>{
    return "<li onclick=selectInput(this)>" + list + "</li>";
  });

  resultsBox.innerHTML = "<ul>" + content.join('') + "</ul>";
}

function selectInput(list) {
  inputBox.value = list.innerHTML;
  resultsBox.innerHTML = '';
}

</script> 
</body>
</html>
